/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Flex;

import Flex.v1.company.leave.LeaveMain;
import java.text.ParseException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ParseException {

        LeaveMain leaveMain = new LeaveMain();
        leaveMain.execute();

    }
}
