/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Flex;

import Flex.v1.company.CompanyMain;
import Flex.v1.company.WorkPolicyMain;
import Flex.v1.company.WorkTypeMain;
import Flex.v1.company.dayoff.DayOffMain;
import Flex.v1.company.leave.LeaveMain;
import java.text.ParseException;

public class App {

    public static void main(String[] args) throws ParseException {

        CompanyMain companyMain = new CompanyMain();
        companyMain.execute();

        WorkTypeMain workTypeMain = new WorkTypeMain();
        workTypeMain.execute();

        WorkPolicyMain workPolicyMain = new WorkPolicyMain();
        workPolicyMain.execute();

        DayOffMain offDaysMain = new DayOffMain();
        offDaysMain.execute();

        LeaveMain leaveMain = new LeaveMain();
        leaveMain.execute();

    }
}
